// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2gc_mzoawrOAkpFM-rEbghKEqqhsUQ7g',
    appId: '1:118387275858:web:85dbd55e4797b9843f878b',
    messagingSenderId: '118387275858',
    projectId: 'chat-2add7',
    authDomain: 'chat-2add7.firebaseapp.com',
    storageBucket: 'chat-2add7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI-JuiDHwPCvMHwEAMYccjjt5Wwrigmfk',
    appId: '1:118387275858:android:e5d8c322832add063f878b',
    messagingSenderId: '118387275858',
    projectId: 'chat-2add7',
    storageBucket: 'chat-2add7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtsuxamsXCzQLqG-U_f1b9sWmlxiilBc',
    appId: '1:118387275858:ios:d6e55d7b010359a23f878b',
    messagingSenderId: '118387275858',
    projectId: 'chat-2add7',
    storageBucket: 'chat-2add7.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtsuxamsXCzQLqG-U_f1b9sWmlxiilBc',
    appId: '1:118387275858:ios:d6e55d7b010359a23f878b',
    messagingSenderId: '118387275858',
    projectId: 'chat-2add7',
    storageBucket: 'chat-2add7.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2gc_mzoawrOAkpFM-rEbghKEqqhsUQ7g',
    appId: '1:118387275858:web:5543574f4d72995e3f878b',
    messagingSenderId: '118387275858',
    projectId: 'chat-2add7',
    authDomain: 'chat-2add7.firebaseapp.com',
    storageBucket: 'chat-2add7.firebasestorage.app',
  );

}